mutation CreateProject($project: ProjectInput!) {
  createProject(project: $project) {
    id
    name
    description
    githubUrl
    liveUrl
    npmName
    monthDownloads: npmDownloads(period: "last-month")
    skillsUsed
    image
  }
}
