query Projects($ids: [String]) {
  projects(ids: $ids) {
    id
    name
    description
    githubUrl
    liveUrl
    npmName
    monthDownloads: npmDownloads(period: "last-month")
    skillsUsed
    brief
    highlights
    image
  }
}
